// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed53a9be-044f-4dc8-a650-596ad443e43a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YzB8nRuLI",
    "aws_user_pools_web_client_id": "4lfqo52u88lqn92e0v9058dcql",
    "oauth": {}
};


export default awsmobile;
